language: python
cache:
  directories:
    - $HOME/.cache/pip
matrix:
  include:
    - python: 3.7
      env: TOXENV=docs
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
install:
  - sudo apt install make
  - pip install tox
script:
  - make tests
